### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by yugirules808** [frifox/gw2dps#11]
I'm using the exe and dll and it works fine whenever I move around in pve or even to and fro from wvw, but the moment i go to character select and try to use the hotkeys on the next character it crashes. What should I do?

**Comment by frifox** [comment]
Works for me, Unless I can reproduce it, can't really fix it.

**Comment by yugirules808** [comment]
Thought it might be GW2PAO causing the clash, took that out and still didn't work nevermind I'll just relog when changing characters if need be
