### ISSUE TITLE
Binary Files

### ISSUE THREAD

**Issue by wizorald** [frifox/gw2dps#14]
Hi ,

Can you put the updated compile version of your last version patch. Can you create a files with a good explain how to compile the program please.

Thanx !

**Comment by frifox** [comment]
Cubimon tweaked the code but now I can't fucking get cmake to find wxwidgets / boost nor can I get it to compile anything. Until I figure this out why, I can't really upload anything.

**Comment by wizorald** [comment]
Thanx for your answers, Good luck to find the error , i will continu to follow your project

**Comment by Cubimon** [comment]
You have to set the environment variables WXWIDGET_ROOT and BOOST_ROOT or you modify the CMakeLists.txt. If it worked earlier for you, you can look up the commit diffs.

**Comment by frifox** [comment]
Yeah, I checked cmake's search scripts and figured as much and set the env vars as needed. But it still compains that both wxwidget and boost are not found. I'm getting a feeling it's somethign else that I'm missing... just not sure what exactly.

**Comment by Cubimon** [comment]
Today I set up the everything on my notebook with the current guide and the build works now, I also added a little about wxwidgets to the readme. The only problem I had was with vs 2015 and wxwidgets, a symbol (sprintf or something like that) was redefined.

**Comment by frifox** [comment]
Figured it out. Source and binaries updated.

**Comment by wizorald** [comment]
Very thanx !
