### ISSUE TITLE
error on launching

### ISSUE THREAD

**Issue by totano** [frifox/gw2dps#16]
OS Windows 10.
gw2dps 2015-09-29

On launching the extracted exe, an error window shows with info message:
*** Caught unhandled unknown exception; terminating

**Comment by frifox** [comment]
Unless I can replicate the issue I cannot fix it. I'm running Windows 10 as well and have no issues running it.

At this moment, all I can recommend are the generics,
- Running exe as Administrator
- Turning off Antivirus
- Updating all drivers & installing os updates
- Reinstalling all redist packages

**Comment by Seviryn** [comment]
Having the same issue, also on Windows 10, none of the above fixed it. Also tried previous versions just to check, got the same error.

**Comment by frifox** [comment]
Inactive issue, closing.
