### ISSUE TITLE
64bit client help?

### ISSUE THREAD

**Issue by indigent** [frifox/gw2dps#22]
Maybe it is time i take matters into my own hands with manual builds,but i thought i might ask before i bang my head on a wall for hours.  Is it even possible to get this to work with 64bit client or should i jus stick to ol faithful.  THanks for taking the time

**Comment by frifox** [comment]
If 32bit isn't crashing on you you can just keep using it as current gw2dps as before. Go 64bit gw2 only if 32bit gw2 is crashing for you. As far as 64bit, seems it's a bit more involved that I thought so it won't be as easy as flipping a switch, as far as I know...

**Comment by indigent** [comment]
thank you for getting back to me.  and sorry if the question sounded patronizing as im sure a lot of effort goes into this.  the 32bit client does randomly crash for me, is why i enjoyed the 64bit exe.  i do really appreciate you taking the time to keep users informed. thank you very mcuh

**Comment by Keridos** [comment]
Yes indeed, A version for the 64-bit client would be awesome. For me and most of my friends the 32 bit version does randomly crash in the newer maps from HoT so we all use the 64bit client at this point.

**Comment by Pluckerpluck** [comment]
I'd like to add my interesting in a 64 bit client. The 32bit crashes fairly regularly in new maps (and raids!) so I'd like to be able to move on fully to the 64 bit client.

**Comment by frifox** [comment]
I'm running 32bit and it's working perfect for me so there are currently no plans to make the x64 build of gw2dps. However, the project is open source and if there is someone who has the knowledge and can make a x64 build, feel free to do so.

**Comment by hairys** [comment]
64-bit work in progress. Try doing a manual x64 build using the latest repos from frifox and rafzi. I'm sure frifox will have x64 binaries ready in no time =)

**Comment by Shawn538** [comment]
Ive tried out the injector on 64 bit. It saya it injects, but using any of the alt + (whatever) keys does nothing. So im assuming its not working for me..

**Comment by hairys** [comment]
Need to do a separate x64 build of both the injector and the dll. Meaning the entire build environment needs to be all x64 (boost library, wxWidgets -> all need to be x64). The pre-release from frifox is 32-bit only, so it will never work on 64-bit clients.

**Comment by hairys** [comment]
Screenshot (note the lack of *32 after the .exe names):
![64bit](https://cloud.githubusercontent.com/assets/10733642/11426111/a715f596-9427-11e5-8e04-c79f6475b8a2.png)

**Comment by frifox** [comment]
Yeah, that much I did figure out. Guess that time it "worked" was me somehow running x86 and thinking it was x64.

**Comment by frifox** [comment]
x64 build is up.
