### ISSUE TITLE
99% health on full health targets

### ISSUE THREAD

**Issue by Wethospu** [frifox/gw2dps#23]
Fractal scale 13 Archdiviner.

Shows "Selected: 782,357 / 782,357 [99%]"

**Comment by frifox** [comment]
Does this happen every time, ie you get to archdiviner (not attacking him yet) and every time you inject gw2dps it will immediately show 99%?

**Comment by Wethospu** [comment]
Yes, whenever I go to that fractal it shows 99%. Even after attacking and resetting.

**Comment by frifox** [comment]
Can you try the latest build and see if it still shows 99%?

**Comment by hairys** [comment]
I was able to reproduce this issue. Commit 682cc18 fixes it. You can close this issue.
