### ISSUE TITLE
Raw defiance values

### ISSUE THREAD

**Issue by Wethospu** [frifox/gw2dps#24]
Different enemies have different amount of raw defiance. So showing it like health "X / Y [Z%]" would be better.

**Comment by frifox** [comment]
Hairys added breakbar feature to gw2lib and its a float value, meaning the percentage isn't calculated but is exactly what gw2 client provides. I haven't dug around to see if there are also the exact breakbar values but for now, percentage is all we can do.

**Comment by frifox** [comment]
Dug around the memory last night for 30 mins. Couldn't find any definite values for the bar, only a 0 to 1 float identifying the percentage. I may dig around some more but it's not looking pretty, it's as if anet keeps the values and calculation server-side and feeds the client only the final % value.

**Comment by Wethospu** [comment]
Looks like they have learned something. :)

**Comment by frifox** [comment]
Fortunately, that percentage has a pretty high precision (more decimal places that we'd ever care about). Can record by how much each skill/condi affects the bar and then take the lowest one as the common denominator as make it equal to "1" breakbar unit.

**Comment by Wethospu** [comment]
More precision would be great since Chill seems to remove like 1.33% per tick.

**Comment by frifox** [comment]
made it show percent down to 5 decimal places. see the latest release for the new build
