### ISSUE TITLE
Meter broken after 11/19 patch

### ISSUE THREAD

**Issue by Anthrozil7** [frifox/gw2dps#25]
![2015-11-20_13-44-04](https://cloud.githubusercontent.com/assets/15947855/11310026/dd59df04-8f8c-11e5-8f49-c1ed59e21918.jpg)
![2015-11-20_13-46-18](https://cloud.githubusercontent.com/assets/15947855/11310070/1d01da1c-8f8d-11e5-88b9-3edb75e1c5ee.jpg)

Health values appear to be broken for both allies and enemies.  The actual DPS values aren't showing up either.

**Comment by frifox** [comment]
Offsets changed. Fortunately rafzi already updated these offsets in his gw2lib repo. Once I get home from work I'll recompile and push updated gw2dps.

**Comment by Anthrozil7** [comment]
Thanks!  :D
