### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by Bjarkil** [frifox/gw2dps#3]
Hi,

I've been using this program for a while now.
I recently got a new computer and I installed this program again this morning.
But although it loads up, i don't get any data.

Here is a screen:
http://puu.sh/emy5V/b5a3a2eb99.jpg

**Comment by frifox** [comment]
Unless I can replicate the problem I can't really fix the problem. The app has no logging or diagnostic tools built in. I ran it today and everything was ok for me. Best I could suggest at this moment is for you to try restarting the PC and then seeing how things to under a clean environment such as new windows user profile and fresh gw2 installation. Sorry I couldn't help more.

**Comment by Bjarkil** [comment]
I restarted my pc and now it's working again.
Thanks!
