### ISSUE TITLE
question regarding the functions of the program

### ISSUE THREAD

**Issue by Shawn538** [frifox/gw2dps#34]
1st, 64 BIT YASSSSSSS I LOVE YOU GUYS
2nd, i know this isnt an issue.. but i dont know where else to post something like this. 

Ok, so when i use [alt] + 5 (or any other recording function) to record damage hits to a file, Where is that file located? / How do i go about setting up a file for it to write to? 

---------------------------------------
Slightly off topic
Also, for the interest of raids, Is there a possibility of seeing the dps of individual players in my raid squad?

**Comment by frifox** [comment]
The monitors dump data into txt files, which will be written to the same folder as the GW2 executable. Filenames are hardcoded in /gw2dps/gw2dps.cpp file lines 27, 44, and 54. 

No, you cannot see individual player's DPS. gw2dps calculates DPS by seeing how much enemy's HP changed over time, ie change over 1 sec.

**Comment by Shawn538** [comment]
Hey frifox, i have an idea for the program. I think you might have thought of this... but ill throw it out there anyways. 

So a lot of people want to know personal dps in group content. I think there is a way to do it without writing a whole new program.

I dont claim to have any proper coding knowledge. I know some java from college. minimal C++. 
So here is my idea. You know when you hit an enemy, the game spits out a damage "splat" over the boss. Well it would not make sense to create an image with upwards of a 500,000 different number splats used as a sprite. That would be silly. I (assume) think that the user client hits a mob, and then passes a value to the server, and the server generates a "splat" based on that number. 

Could that data that's being passed to the "Splat Class" be read in the memory, added up and calculated? 
This would give super accurate personal dps, as the splats only show your own hits. This rule applies for normal damage, as well as condition damage.

**Comment by hairys** [comment]
I've actually been exploring a variation of this idea. Read the combat log before it converts the numbers into text and puts it in to the chat window. I managed to find the offsets for the chat log, but I want to go further "up the chain" to find where the actual numbers are.

**Comment by Shawn538** [comment]
That would work too. The combat log records the numbers whether you have them activated for viewing or not. However (i presume) the damage itself comes from the server. So unless you want to get into the hack-y, blurry areas.. that method might be extra dangerous.

**Comment by frifox** [comment]
Inactive issue, closing.
