### ISSUE TITLE
Dec 1 patch

### ISSUE THREAD

**Issue by frifox** [frifox/gw2dps#35]
Yes, it's broken. I got 32bit build to work, x64 still has few issues such as reading object/world-boss HP's.

Once those are figured out I'll push the new release.

**Comment by hairys** [comment]
Your shift values are fine, they didn't change. A few offsets changed in hacklib_gw2. Check my latest pull request in rafzi's repo.

**Comment by frifox** [comment]
Yeah, I used those for the pre-release build. Maybe I missed something, will have to check...
