### ISSUE TITLE
MAC client support

### ISSUE THREAD

**Issue by fuson** [frifox/gw2dps#36]
All in topic :) Mac users need hardcore assistant too!

**Comment by hairys** [comment]
I don't own a mac so I've never played the mac client. I know that the mac client uses TransGaming's Cider engine, which is basically Wine under the hood. What I wanna know is if it uses the same binary as the PC version. AFAIK, hacklib has unix support in the code, but I wonder if we need to change anything in hacklib_gw2 or gw2dps.
Need to find a good guide for setting up a hackintosh with the lastest Mac OSX :)

**Comment by frifox** [comment]
Highly unlikely.
