### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by wizorald** [frifox/gw2dps#4]
Hello,

I wondered if it was possible to add the ability to place the information window to location of our choice on our screen? So it is possible to meter the Show Floaters information in a different color to ally and enemy?

Thank you very much I love your program

**Comment by frifox** [comment]
Element location and floater colors are hardcoded. You'd need to edit the coordinates and color values per your preference and re-compile the dll. Currently there is no easy way to customize it as you want.

**Comment by wizorald** [comment]
Thank you for your response.

I already try to look at the code but I can not put back. I program in VB.net and I do not understand the C ++ coding structure. To honestly say I had great difficulty opening it in visual studio and I never managed to compile. I even try to find the information displayed by alternative aurte its still unsuccessful.

Too bad it's not in VB.net is the kind of code that I would have had so much fun to look at and understand.

good luck
