### ISSUE TITLE
why does this have to inject ?

### ISSUE THREAD

**Issue by realestninja** [frifox/gw2dps#41]
Injecting means that it hooks into the client. Isn't it supposed to JUST READ the chat ? I doubt that hooking into the client makes this LEGAL.

**Comment by Anthrozil7** [comment]
No one is claiming that this meter just reads chat.  Frifox's gw2dps is far older than jaxnX or the new "gw2dps" meter that failed to do their research before picking a name.  Those are the two that use OCR on chat.

**Comment by frifox** [comment]
What Anthrozil7 said.

**Comment by realestninja** [comment]
sorry, was my mistake!
