### ISSUE TITLE
tabs to spaces

### ISSUE THREAD

**Issue by hairys** [frifox/gw2dps#42]
Hey frifox, mind if I convert all the gw2dps code tabs to spaces? That way I don't have to keep switching between the two types when committing to hacklib and gw2dps (rafzi uses spaces).

**Comment by frifox** [comment]
Go ahead, and in fact that's one of things I'd like but never got to do, I prefer spaces as well. The IDE I use at work (PhpStorm) handles them very well and the code portability becomes much better. The Visual Studio kinda forced the tabs on me and I never bothered checking how to make it do spaces instead.

**Comment by hairys** [comment]
Cool, expect to see a rather large commit soon :)

**Comment by hairys** [comment]
commit: 2316c20
