### ISSUE TITLE
Enemy ids

### ISSUE THREAD

**Issue by Wethospu** [frifox/gw2dps#44]
Would it be possible to get the tool show enemy ids? I previously used another tool but it's no longer updated.

The creator told me that 

"There's a flag in the character class telling you if the character is a player or an npc. The 16 lowest bit of that flag are the Id of the npc."

"struct{ unsigned dataId : 28; unsigned type : 4;  };
it used to be at 0x44 of characters"

I need enemy ids to connect them to datamined raw data (attributes and coefficients). Thanks!

**Comment by hairys** [comment]
Hey Wethospu, do you know if it is 16 or 28 bits? There seems to be a conflict in your quote. This is new to me and I'm testing to see if the IDs remain consistent across map loads.

**Comment by hairys** [comment]
Also, I would assume these IDs are per map as 16-bits is awfully small to be useful as any kind of GUID.

**Comment by Wethospu** [comment]
Sorry, I don't really know more. Here are some known ids which hopefully helps you to figure it out:

Vale Guardian id 15438.
Red Guardian id 15393.
Blue Guardian id 15406.
Green Guardian id 15382.

**Comment by frifox** [comment]
What tool was did you use? Is source available?

**Comment by Wethospu** [comment]
The tool wasn't public and sources are lost.

**Comment by hairys** [comment]
Are there any IDs, that you know of, over 65536? that will determine if it's 28-bit.

**Comment by Wethospu** [comment]
Highest id I know is like 16000.

**Comment by hairys** [comment]
Alright, I'll stick with 16-bit for now. Gonna edit my previous release in a bit, then close this issue.

**Comment by hairys** [comment]
release: https://github.com/frifox/gw2dps/releases/tag/2016-08-27

**Comment by Wethospu** [comment]
Sweet, thanks!
