### ISSUE TITLE
(0xc000007b)

### ISSUE THREAD

**Issue by indigent** [frifox/gw2dps#45]
cant figure out what to do after i upgraded to windows10 i downloaded the lastest version and got an application error (after installing all proper dll from vc_redist) of the application was unable to start correctly (0xc000007b).  

any ideas? thanks for reading this

**Comment by hairys** [comment]
Try installing the 2015 C++ redist (both 32-bit and 64-bit):
https://www.microsoft.com/en-us/download/details.aspx?id=48145

And make sure you have DirectX installed:
https://github.com/frifox/gw2dps/releases/download/redist/dxwebsetup.exe

**Comment by indigent** [comment]
thnx, after a few more days of  searching, i havent come up with a solution but its a "my end" thing with broken .dll after win10 update, thnx for your help though
