### ISSUE TITLE
Feature request: class symbol/HP floaters separation

### ISSUE THREAD

**Issue by Hagens82** [frifox/gw2dps#46]
Would it be possible to separate out the class symbol/HP floaters so you can choose to see them individually or together? Above a certain number of players it becomes very cluttered.
Thanks for your time.

**Comment by hairys** [comment]
There is a class filter atm (default ALT+V) that you could try. Another option would be to show only the locked target's floater.

**Comment by Hagens82** [comment]
First off I want to thank you for all your work in upgrading and maintaining this tool. It truly has made a world of difference to how I experience the game. I don't want to come across as pushy. Just suggesting a possible QoL change.

The class filter is indeed an extremely handy addition, but in wvw or guild area where people are stacked in a tight ball, the hp floaters become unreadable and at that stage it's just visual clutter. For my personal situation, I'd like to be able to see where all classes are via their symbol floaters, but then flash on/off HP floaters to know what builds people are running.

Thanks for your time.

**Comment by snakelayer** [comment]
> to know what builds people are running.

I'm kinda curious about what you're trying to do.
Can I assume you are a WvW commander and want a quick way to know what your squad is composed of? And currently, you're using the HP values to infer player builds?

**Comment by hairys** [comment]
> I'd like to be able to see where all classes are via their symbol floaters, but then flash on/off HP floaters
This makes me think you want to be able to turn off the white text on floaters and only show the class symbols. If that's the case, I can add a keybind that will toggle floater text on/off.

**Comment by Hagens82** [comment]
> This makes me think you want to be able to turn off the white text on floaters and only show the class symbols. If that's the case, I can add a keybind that will toggle floater text on/off.

That's exactly what I'm after yes. Apologies if my previous posts didn't make that clear.

**Comment by hairys** [comment]
wish granted: https://github.com/frifox/gw2dps/releases/tag/2016-12-13

**Comment by Hagens82** [comment]
Thanks Santa
