### ISSUE TITLE
Selected Target Details

### ISSUE THREAD

**Issue by Hagens82** [frifox/gw2dps#47]
Have the target details for stats (power/toughness etc) not been hooked in or is this user build error on my part?

Thanks.

![stat](https://cloud.githubusercontent.com/assets/24514187/21142302/688c9ec0-c139-11e6-9319-d5007458cf20.png)

**Comment by hairys** [comment]
The server doesn't supply stats for all targets. Only pets that you control will show stats.

**Comment by frifox** [comment]
I haven't gotten a chance to test myself, but have you tried this one?
https://www.deltaconnected.com/arcdps/

"panel: gearcheck
 any in-visual-range character gear check."

**Comment by hairys** [comment]
I haven't checked arcdps. I don't think I will either.  
I know about the "gearcheck" thing. I was able to find the offsets myself (it was rather easy). idk when I'll implement it.

**Comment by Hagens82** [comment]
I've now tried arcdps and it has some nice features, but unfortunately the gearcheck and many other features are indeed locked to raid/specific game modes which kinda kills its usefulness.

![traits](https://cloud.githubusercontent.com/assets/24514187/21671618/8ab02f52-d314-11e6-8b44-0afca2c614bd.png)
![gear](https://cloud.githubusercontent.com/assets/24514187/21671627/8fa37262-d314-11e6-8708-1dd14193989d.png)
