### ISSUE TITLE
Does not work with the latest update

### ISSUE THREAD

**Issue by Cubimon** [frifox/gw2dps#5]
hp and dps is not shown, maybe more does not work

**Comment by Cubimon** [comment]
Rafi's lib is updated

**Comment by frifox** [comment]
Yeah, I updated the dll last night.

**Comment by PartyLich** [comment]
frifox,

First, thanks for the efforts! Fun stuff.
The compiled dll you have in the repo works without issue, but when building from your source (and rafzi's) I get the same offset-ish problem as above (no data, just empty displays). 
I imagine you don't have much/any time to troubleshoot random strangers, but if you have any offhand guesses about where I may have gone wrong I'd definitely appreciate it.

**Comment by ridicul0us** [comment]
Hi, Anyone why the floater doesn't update the agent's health on my computer?
