### ISSUE TITLE
UI doesn't show up

### ISSUE THREAD

**Issue by Pluckerpluck** [frifox/gw2dps#6]
So, I can't tell if this is just me or not, but my UI no longer shows up (it did before).

Running the exe will still hook hotkeys, so I know the dll is injecting. But no information is available on screen (and yes, I've tried the hide hotkey).

Is this an issue with the latest patch or something on my end?

**Comment by frifox** [comment]
GW2 updated and broke it. I pushed an update last night so it should be fixed now.
