### ISSUE TITLE
Unhandled SEH exception

### ISSUE THREAD

**Issue by sm-k** [frifox/gw2dps#8]
when running gw2dps.exe i get this error after latest patch

ps thank you dennis!

**Comment by Nunoma** [comment]
I'm also getting this message

Aside from that little thingy; thanks a lot for developing this tool

**Comment by frifox** [comment]
Yep, aware of this issue. No ETA when it'll be fixed, probably going to wait for rafzi to update his gw2lib. I believe it's a problem with pattern searching, anet changed the code enough that old patterns/offsets aren't valid anymore.

**Comment by Nunoma** [comment]
Okey, thanks for the info. I hope it will be fixed soon
Have a good one

**Comment by frifox** [comment]
Patched.

**Comment by sm-k** [comment]
praise
