### ISSUE TITLE
Release and Readme

### ISSUE THREAD

**Issue by Cubimon** [frifox/gw2dps#9]
You should add your releases to https://github.com/frifox/gw2dps/releases and reference your repository in your readme. You may also mention where releases are in the readme.

**Comment by frifox** [comment]
Probably. I've only used github to host my code for reference only so still new the idea of actually maintaining/releasing a public project on git. Heck, even the files on my hdd don't actually match the structure (and content) here on git so I probably should square that away first XD

**Comment by frifox** [comment]
Done.
